### API Testing for DATAFORLIFE
### Variables
@adminUser = admin
@adminPass = secret
@host = http://localhost:8220
@apiPrefix = /api

@token = login-success.response.body.token

### Health Check (root)
GET {{host}}/

### API Root (prefixed)
GET {{host}}{{apiPrefix}}/

### Auth Login - success
# @name login-success
POST {{host}}{{apiPrefix}}/auth/login
Content-Type: application/json

{
	"username": "{{adminUser}}",
	"password": "{{adminPass}}"
}

### Admin Get Board
GET {{host}}{{apiPrefix}}/admin/get-board/2766949
Content-Type: application/json

###
POST {{host}}{{apiPrefix}}/admin/selected-area
Content-Type: application/json

{
	"north": 11.159871119602483,
    "south": 10.375438568758025,
    "east": 107.02445924184507,
    "west": 106.35742462311387
}
